---
sidebar: sidebar 
permalink: troubleshooting.html 
keywords: troubleshooting, trident 
summary: Trident를 설치하고 사용하는 동안 발생할 수 있는 문제를 해결하려면 여기에 제공된 포인터를 사용하십시오. 
---
= 문제 해결
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident를 설치하고 사용하는 동안 발생할 수 있는 문제를 해결하려면 여기에 제공된 포인터를 사용하십시오.


NOTE: Trident에 대한 도움이 필요하면 를 사용하여 지원 번들을 만든 `tridentctl logs -a -n trident` 후 NetApp 지원 팀에 보내십시오.



== 일반 문제 해결

* Trident Pod가 제대로 작동하지 않는 경우(예: Trident Pod가 2개 미만의 컨테이너로 진행되는 단계에서 중단 `ContainerCreating`), 를 실행하고 `kubectl -n trident describe deployment trident` 추가 통찰력을 제공할 수 있습니다. `kubectl -n trident describe pod trident-********-****` kubelet 로그(예: 를 통해)를 얻는 `journalctl -xeu kubelet` 것도 도움이 될 수 있습니다.
* Trident 로그에 충분한 정보가 없으면 설치 옵션에 따라 install 매개 변수에 플래그를 전달하여 Trident에 대한 디버그 모드를 활성화해 볼 수 `-d` 있습니다.
+
그런 다음 로그에서 를 사용하여 디버그가 설정되고 `./tridentctl logs -n trident` 검색되는지 확인합니다. `level=debug msg`

+
운영자와 함께 설치됩니다::
+
--
[listing]
----
kubectl patch torc trident -n <namespace> --type=merge -p '{"spec":{"debug":true}}'
----
그러면 모든 Trident 포드가 다시 시작됩니다. 이 작업은 몇 초 정도 걸릴 수 있습니다. 의 출력에서 '연령' 열을 관찰하여 확인할 수 `kubectl get pod -n trident` 있습니다.

Trident 20.07 및 20.10의 경우 `tprov` 대신 `torc` 을 사용하십시오.

--
헬름과 함께 설치::
+
--
[listing]
----
helm upgrade <name> trident-operator-21.07.1-custom.tgz --set tridentDebug=true`
----
--
tridentctl과 함께 설치됩니다::
+
--
[listing]
----
./tridentctl uninstall -n trident
./tridentctl install -d -n trident
----
--


* 백엔드 정의에 포함하여 각 백엔드에 대한 디버그 로그를 얻을 수도 `debugTraceFlags` 있습니다. 예를 들어, Trident 로그에 API 호출 및 메서드 트래버스를 가져오려면 를 `debugTraceFlags: {"api":true, "method":true,}` 포함합니다. 기존 백엔드는 로 `tridentctl backend update`구성할 수 `debugTraceFlags` 있습니다.
* RHCOS(Red Hat Enterprise Linux CoreOS)를 사용하는 경우 작업자 노드에서 이 `iscsid` 활성화되고 기본적으로 시작되는지 확인합니다. 이 작업은 OpenShift MachineConfigs를 사용하거나 점화 템플릿을 수정하여 수행할 수 있습니다.
* 에서 Trident를 사용할 때 발생할 수 있는 일반적인 https://azure.microsoft.com/en-us/services/netapp/["Azure NetApp Files"] 문제는 충분한 권한이 없는 앱 등록에서 테넌트 및 클라이언트 암호가 오는 경우입니다. Trident 요구 사항의 전체 목록은 link:trident-use/anf.html["Azure NetApp Files"]구성을 참조하십시오.
* PV를 컨테이너에 장착하는 데 문제가 있으면 가 설치되어 실행 중인지 `rpcbind` 확인합니다. 호스트 OS에 필요한 패키지 관리자를 사용하고 가 실행 중인지 `rpcbind` 확인합니다. 또는 이와 동등한 를 실행하여 서비스 `systemctl status rpcbind` 상태를 확인할 수 `rpcbind` 있습니다.
* Trident 백엔드에서 이전에 작업한 적이 있음에도 불구하고 상태가 지속되었다고 보고할 경우 `failed` 백엔드와 연결된 SVM/관리자 자격 증명을 변경하여 발생할 수 있습니다. Trident POD를 사용하거나 바운싱하여 백엔드 정보를 업데이트하면 `tridentctl update backend` 이 문제가 해결됩니다.
* Docker를 컨테이너 런타임으로 사용하여 Trident를 설치할 때 권한 문제가 발생하면 플래그를 사용하여 Trident 설치를 `--in cluster=false` 시도합니다. 설치 프로그램 포드를 사용하지 않으며 사용자 때문에 권한 문제가 발생하지 `trident-installer` 않습니다.
* 실행 실패 후 정리할 때 를 `uninstall parameter <Uninstalling Trident>` 사용합니다. 기본적으로 이 스크립트는 Trident에서 만든 CRD를 제거하지 않으므로 실행 중인 구축에서도 안전하게 제거한 후 다시 설치할 수 있습니다.
* 이전 버전의 Trident로 다운그레이드하려면 먼저 `tridentctl uninstall` 명령을 실행하여 Trident를 제거하십시오. 원하는 를 https://github.com/NetApp/trident/releases["Trident 버전"] 다운로드하고 명령을 사용하여 `tridentctl install` 설치합니다.
* 설치가 성공적으로 완료된 후 PVC가 해당 단계에 `kubectl describe pvc` 고착되면 `Pending` Trident가 이 PVC에 대한 PV를 프로비저닝하지 못한 이유에 대한 추가 정보를 제공할 수 있습니다.




== 연산자를 사용한 Trident 배포 실패

연산자를 사용하여 Trident를 배포하는 경우 의 상태가 `TridentOrchestrator` 에서 `Installing` 로 `Installed`변경됩니다. 상태를 확인한 후 운용자가 스스로 복구할 수 없는 경우 `Failed` 다음 명령어를 실행하여 운용자의 로그를 확인해야 한다.

[listing]
----
tridentctl logs -l trident-operator
----
삼원 운영자 컨테이너의 로그를 뒤로하면 문제가 있는 위치를 가리킬 수 있습니다. 예를 들어, 이러한 문제 중 하나는 Airgapped 환경의 업스트림 등록부에서 필요한 컨테이너 이미지를 가져올 수 없는 것일 수 있습니다.

Trident 설치가 실패한 이유를 이해하려면 상태를 확인해야 `TridentOrchestrator` 합니다.

[listing]
----
kubectl describe torc trident-2
Name:         trident-2
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  trident.netapp.io/v1
Kind:         TridentOrchestrator
...
Status:
  Current Installation Params:
    IPv6:
    Autosupport Hostname:
    Autosupport Image:
    Autosupport Proxy:
    Autosupport Serial Number:
    Debug:
    Image Pull Secrets:         <nil>
    Image Registry:
    k8sTimeout:
    Kubelet Dir:
    Log Format:
    Silence Autosupport:
    Trident Image:
  Message:                      Trident is bound to another CR 'trident'
  Namespace:                    trident-2
  Status:                       Error
  Version:
Events:
  Type     Reason  Age                From                        Message
  ----     ------  ----               ----                        -------
  Warning  Error   16s (x2 over 16s)  trident-operator.netapp.io  Trident is bound to another CR 'trident'
----
이 오류는 Trident 설치에 사용된 가 이미 있음을 `TridentOrchestrator` 나타냅니다. 각 Kubernetes 클러스터에는 하나의 Trident 인스턴스만 있을 수 있으므로 운영자는 생성할 수 있는 활성 인스턴스가 하나만 존재하도록 `TridentOrchestrator` 보장합니다.

또한 Trident Pod의 상태를 관찰하면 무언가 잘못되었음을 나타내는 경우가 많습니다.

[listing]
----
kubectl get pods -n trident

NAME                                READY   STATUS             RESTARTS   AGE
trident-csi-4p5kq                   1/2     ImagePullBackOff   0          5m18s
trident-csi-6f45bfd8b6-vfrkw        4/5     ImagePullBackOff   0          5m19s
trident-csi-9q5xc                   1/2     ImagePullBackOff   0          5m18s
trident-csi-9v95z                   1/2     ImagePullBackOff   0          5m18s
trident-operator-766f7b8658-ldzsv   1/1     Running            0          8m17s
----
하나 이상의 컨테이너 이미지를 가져오지 않았기 때문에 포드를 완전히 초기화할 수 없다는 것을 분명히 알 수 있습니다.

이 문제를 해결하려면 CR을 편집해야 `TridentOrchestrator` 합니다. 또는 을 삭제하고 수정되고 정확한 정의를 사용하여 새 정의를 만들 수 `TridentOrchestrator` 있습니다.



== 를 사용한 Trident 배포 실패 `tridentctl`

어떤 문제가 발생했는지 쉽게 알 수 있도록 인수를 사용하여 설치 프로그램을 다시 실행할 수 있습니다``-d``. 이렇게 하면 디버그 모드가 설정되고 문제가 무엇인지 이해하는 데 도움이 됩니다.

[listing]
----
./tridentctl install -n trident -d
----
문제를 해결한 후 다음과 같이 설치를 정리한 다음 명령을 다시 실행할 수 있습니다 `tridentctl install`.

[listing]
----
./tridentctl uninstall -n trident
INFO Deleted Trident deployment.
INFO Deleted cluster role binding.
INFO Deleted cluster role.
INFO Deleted service account.
INFO Removed Trident user from security context constraint.
INFO Trident uninstallation succeeded.
----


== Trident 및 CRD를 완전히 제거합니다

Trident와 생성된 모든 CRD 및 관련 사용자 지정 리소스를 완전히 제거할 수 있습니다.


WARNING: 이 작업은 취소할 수 없습니다. Trident를 완전히 새로 설치하려는 경우가 아니라면 이 작업을 수행하지 마십시오. CRD를 제거하지 않고 Trident를 제거하려면 을 link:trident-managing-k8s/uninstall-trident.html["Trident를 제거합니다"]참조하십시오.

[role="tabbed-block"]
====
.Trident 운영자
--
Trident를 제거하고 Trident 운영자를 사용하여 CRD를 완전히 제거하려면:

[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"wipeout":["crds"],"uninstall":true}}'
----
--
.헬름
--
Helm을 사용하여 Trident를 제거하고 CRD를 완전히 제거하려면:

[listing]
----
kubectl patch torc trident --type=merge -p '{"spec":{"wipeout":["crds"],"uninstall":true}}'
----
--
.<code> tridentctl </code> 를 참조하십시오
--
를 사용하여 Trident를 제거한 후 CRD를 완전히 제거합니다 `tridentctl`

[listing]
----
tridentctl obliviate crd
----
--
====


== rwx 원시 블록 네임스페이스와 관련된 NVMe 노드 스테이징 해제 실패 o Kubernetes 1.26

Kubernetes 1.26을 실행 중인 경우 rwx 원시 블록 네임스페이스와 함께 NVMe/TCP를 사용할 때 노드 스테이징 해제가 실패할 수 있습니다. 다음 시나리오는 오류에 대한 해결 방법을 제공합니다. 또는 Kubernetes를 1.27로 업그레이드할 수도 있습니다.



=== 네임스페이스 및 Pod를 삭제했습니다

Pod에 Trident 관리 네임스페이스(NVMe 영구 볼륨)가 연결되어 있는 경우를 가정해 보겠습니다. ONTAP 백엔드에서 네임스페이스를 직접 삭제하는 경우, Pod를 삭제하려고 하면 스테이징 프로세스가 중단됩니다. 이 시나리오는 Kubernetes 클러스터나 다른 작동에 영향을 주지 않습니다.

.해결 방법
해당 노드에서 영구 볼륨(해당 네임스페이스에 해당)을 마운트 해제하고 삭제합니다.



=== 데이터 LIF가 차단되었습니다

 If you block (or bring down) all the dataLIFs of the NVMe Trident backend, the unstaging process gets stuck when you attempt to delete the pod. In this scenario, you cannot run any NVMe CLI commands on the Kubernetes node.
.해결 방법
전체 기능을 복원하려면 dataLIFS를 불러옵니다.



=== 네임스페이스 매핑을 삭제했습니다

 If you remove the `hostNQN` of the worker node from the corresponding subsystem, the unstaging process gets stuck when you attempt to delete the pod. In this scenario, you cannot run any NVMe CLI commands on the Kubernetes node.
.해결 방법
를 `hostNQN` 하위 시스템에 다시 추가합니다.
