---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-tridentctl.html 
keywords: deploy, Trident, methods, tridentctl, windows 
summary: '을 사용하여 Trident를 설치할 수 `tridentctl` 있습니다. 이 프로세스는 Trident에 필요한 컨테이너 이미지가 개인 레지스트리에 저장되어 있거나 저장되지 않은 설치에 적용됩니다.' 
---
= tridentctl을 사용하여 설치합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
을 사용하여 Trident를 설치할 수 `tridentctl` 있습니다. 이 프로세스는 Trident에 필요한 컨테이너 이미지가 개인 레지스트리에 저장되어 있거나 저장되지 않은 설치에 적용됩니다. 배포를 사용자 지정하려면 `tridentctl` 을 link:kubernetes-customize-deploy-tridentctl.html["tridentctl 배포를 사용자 지정합니다"]참조하십시오.



== Trident 25.02에 대한 중요 정보

*Trident에 대한 다음 중요 정보를 읽어야 합니다.*

.<strong> Trident </strong>에 대한 중요 정보입니다
[%collapsible%open]
====
* Kubernetes 1.27가 이제 Trident에서 지원됩니다. Kubernetes를 업그레이드하기 전에 Trident를 업그레이드하십시오.
* Trident은 multipath.conf 파일에서 권장 값을 값으로 하여 SAN 환경에서 다중 경로 구성을 엄격히 적용합니다 `find_multipaths: no`.
+
다중 경로 이외의 구성을 사용하거나 `find_multipaths: yes` multipath.conf 파일에서 OR `find_multipaths: smart` 값을 사용하면 마운트 오류가 발생합니다. Trident는 21.07 릴리즈 이후 를 사용할 것을 `find_multipaths: no` 권장합니다.



====


== 를 사용하여 Trident를 설치합니다 `tridentctl`

를 link:../trident-get-started/kubernetes-deploy.html["설치 개요"] 검토하여 설치 사전 요구 사항을 충족하고 환경에 맞는 올바른 설치 옵션을 선택했는지 확인합니다.

.시작하기 전에
설치를 시작하기 전에 Linux 호스트에 로그인하여 제대로 작동하는지, 필요한 Privileges가 있는지 확인합니다link:requirements.html["지원되는 Kubernetes 클러스터"^].


NOTE: OpenShift에서는 다음에 나오는 모든 예제 대신 `kubectl` 를 사용하고 먼저 또는 `oc login -u kube-admin` 를 `oc` 실행하여 * SYSTEM:admin * 으로 `oc login -u system:admin` 로그인합니다.

[%collapsible%open]
====
. Kubernetes 버전 확인:
+
[listing]
----
kubectl version
----
. 클러스터 관리자 권한 확인:
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. Docker Hub의 이미지를 사용하는 Pod를 시작하고 Pod 네트워크를 통해 스토리지 시스템에 연결할 수 있는지 확인합니다.
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


== 1단계: Trident 설치 프로그램 패키지를 다운로드합니다

Trident 설치 프로그램 패키지는 Trident POD를 생성하고, 상태를 유지하는 데 사용되는 CRD 객체를 구성하고, 클러스터 호스트에 볼륨을 프로비저닝하고 연결하는 등의 작업을 수행하기 위해 CSI 사이드카를 초기화합니다. 에서 최신 버전의 Trident 설치 프로그램을 다운로드하고 압축을 link:https://github.com/NetApp/trident/releases/latest["GitHub의 _Assets_섹션"^]풉니다. 선택한 Trident 버전으로 예시에서 _<Trident-installer-XX.X.tar.gz>_를 업데이트하십시오.

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v25.02.0/trident-installer-25.02.0.tar.gz
tar -xf trident-installer-25.02.0.tar.gz
cd trident-installer
----


== 2단계: Trident를 설치합니다

명령을 실행하여 원하는 네임스페이스에 Trident를 `tridentctl install` 설치합니다. 추가 인수를 추가하여 이미지 레지스트리 위치를 지정할 수 있습니다.

[role="tabbed-block"]
====
.표준 모드
--
[listing]
----
./tridentctl install -n trident
----
--
.하나의 레지스트리에 있는 이미지
--
[listing]
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:25.02 --trident-image <your-registry>/trident:25.02.0
----
--
.다른 레지스트리의 이미지
--
[listing]
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:25.02 --trident-image <your-registry>/trident:25.02.0
----
--
====
설치 상태는 다음과 같습니다.

[listing]
----
....
INFO Starting Trident installation.                namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
INFO Added finalizers to custom resource definitions.
INFO Created Trident service.
INFO Created Trident secret.
INFO Created Trident deployment.
INFO Created Trident daemonset.
INFO Waiting for Trident pod to start.
INFO Trident pod started.                          namespace=trident pod=trident-controller-679648bd45-cv2mx
INFO Waiting for Trident REST interface.
INFO Trident REST interface is up.                 version=25.02.0
INFO Trident installation succeeded.
....
----


== 설치를 확인합니다

POD 생성 상태 또는 을 사용하여 설치를 확인할 수 `tridentctl` 있습니다.



=== POD 생성 상태 사용

생성된 Pod의 상태를 검토하여 Trident 설치가 완료되었는지 확인할 수 있습니다.

[listing]
----
kubectl get pods -n trident

NAME                                  READY   STATUS    RESTARTS   AGE
trident-controller-679648bd45-cv2mx   6/6     Running   0          5m29s
trident-node-linux-vgc8n              2/2     Running   0          5m29s
----

NOTE: 설치 프로그램이 성공적으로 완료되지 않거나 (`trident-csi-<generated id>`23.01 이전 버전에서 * 실행 중 * 이 없는 경우 `trident-controller-<generated id>` 플랫폼이 설치되지 않은 것입니다. 을 사용하여 `-d` link:../troubleshooting.html#troubleshooting-an-unsuccessful-trident-deployment-using-tridentctl["디버그 모드를 켭니다"]문제를 해결합니다.



=== 사용 `tridentctl`

를 사용하여 설치된 Trident 버전을 확인할 수 `tridentctl` 있습니다.

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 25.02.0        | 25.02.0        |
+----------------+----------------+
----


== 샘플 구성

다음 예에서는 를 사용하여 Trident를 설치하기 위한 샘플 구성을 `tridentctl` 제공합니다.

.Windows 노드
[%collapsible]
====
Windows 노드에서 Trident를 실행하려면 다음을 따르십시오.

[listing]
----
tridentctl install --windows -n trident
----
====
.강제 분리
[%collapsible]
====
강제 분리에 대한 자세한 내용은 을 link:..trident-get-started/kubernetes-customize-deploy.html["Trident 운영자 설치를 사용자 지정합니다"]참조하십시오.

[listing]
----
tridentctl install --enable-force-detach=true -n trident
----
====